POST http://localhost:8080/api/member/register
Content-Type: application/json

{
  "username": "testing",
  "nickname": "adam2",
  "password": "bin12345"
}

###

POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "username": "testing",
  "password": "bin12345"
}

###

POST http://localhost:8080/api/auth/boards/create
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0aW5nIiwiZXhwIjoxNjY2NjY5NDA2LCJpYXQiOjE2NjY2NjU4MDZ9.k5oUXPWWLvx3Gtu0wKVF4FerolfPrx-OHwm0YMdM8l0

{
  "boardContent": "첫번째 포스트",
  "boardTitle": "배고파"
}





###

GET http://localhost:8080/api/auth/boards
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0aW5nIiwiZXhwIjoxNjY2NTQ1OTIwLCJpYXQiOjE2NjY1NDIzMjB9.st236wqx5nVjcXQAqF8s_miggDPEwAKHPK1hdIH8mqQ

###

GET http://localhost:8080/api/auth/boards/1
Content-Type: application/json
Access_Token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0aW5nIiwiZXhwIjoxNjY2NTQxNjYyLCJpYXQiOjE2NjY1MzgwNjJ9.irPr48mocrkH8KapKsnWsFek8iqy3tKu0YKWf7dfSXQ

###

PUT http://localhost:8080/api/auth/boards/6
Content-Type: application/json
Access_Token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0aW5nIiwiZXhwIjoxNjY2NTQ1OTIwLCJpYXQiOjE2NjY1NDIzMjB9.st236wqx5nVjcXQAqF8s_miggDPEwAKHPK1hdIH8mqQ

{
  "content": "이것도 테스트용",
  "title": "이건 테스트용"
}

###

GET http://localhost:8080/api/member/id/test22ing
Content-Type: application/json


###

DELETE http://localhost:8080/api/auth/boards/4
Content-Type: application/json
Access_Token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0aW5nIiwiZXhwIjoxNjY2NTQ1OTIwLCJpYXQiOjE2NjY1NDIzMjB9.st236wqx5nVjcXQAqF8s_miggDPEwAKHPK1hdIH8mqQ


###

POST http://localhost:8080/api/auth/board/comment/1
Content-Type: application/json
Access_token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtU2Vjb25kIiwiZXhwIjoxNjY2MzM2MTU0LCJpYXQiOjE2NjYyNDk3NTR9.bgc06N_bcsPFicwxCbgUBT-kG3TJYwfLh4eTZIVhWCQ

{
  "content": "cococooment"
}
###

GET http://localhost:8080/api/auth/board/comment
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtU2Vjb25kIiwiZXhwIjoxNjY2MjcxMzQ0LCJpYXQiOjE2NjYxODQ5NDR9.vLMmhoBNeSWdRaCoxqKHmDqsePSyEwhPzhy-spnuvbY



###


GET http://localhost:8080/api/issue/token
Accept: application/json
Refresh_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3b25iaW4zQGdtYWlsLmNvbSIsImV4cCI6MTY2NjEwMTQzNSwiaWF0IjoxNjY2MDE1MDM1fQ.qoilL1J0v22nDYG7kN-aD665EHUWlIt-nL3PwbUPT-A

###
POST http://localhost:8080/api/member
Content-Type: application/json

{
  "username": "wonbin@mail.com",
  "password": "bin1234"
}

###

GET http://localhost:8080/api/auth/boards
Content-Type: application/json
Access_Token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtU2Vjb25kIiwiZXhwIjoxNjY2MjQ2NTkyLCJpYXQiOjE2NjYxNjAxOTJ9.OnVZUmzEtl_MyIg7hgh-WRLeFkaZZdv5sGE8tKmWEEM

###

DELETE http://localhost:8080/api/auth/boards/delete/1
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtU2Vjb25kIiwiZXhwIjoxNjY2MTg3Mjk4LCJpYXQiOjE2NjYxMDA4OTh9._sVp2TPHOXuBu57FcbKbz-KhUw9A6YjNsI4N_4vR_tg
###

PUT http://localhost:8080/api/auth/boards/update/2
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtU2Vjb25kIiwiZXhwIjoxNjY2MjY0NDM0LCJpYXQiOjE2NjYxNzgwMzR9.HDTdREpm8gK4DHnu0Db44E-3WQ620YuvAQ8rZWiqXq4

{
  "title": "zzzz Title"
}

###
POST http://localhost:8080/api/auth/heart/like/1
Content-Type: application/json
Access_Token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtU2Vjb25kIiwiZXhwIjoxNjY2MzM0MjYxLCJpYXQiOjE2NjYyNDc4NjF9.OyIja8YgLcPfHSSR5w12APxL1pYMdVWOHUBiKYNU9Zo





