POST http://localhost:8080/member/register
Content-Type: application/json

{
  "username": "adamparker",
  "nickname": "adampark",
  "password": "bin12345"
}

###

POST http://localhost:8080/member/login
Content-Type: application/json

{
  "username": "adamparker",
  "password": "bin12345"
}

###

POST http://localhost:8080/auth/boards/create
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtcGFya2VyIiwiZXhwIjoxNjcwNDU0Mzg2LCJpYXQiOjE2NjY4NTQzODZ9.ANWfx11O1JL8lfWGZ52L9mr4ptTRvlrf4WxjXJBL8S8

{
  "boardContent": "어른이 되서 깨어납니다",
  "boardTitle": "어제는 어릴때로 돌아가서"
}


###

GET http://localhost:8080/boards
Content-Type: application/json


###

POST http://localhost:8080/auth/4/DISLIKE/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtcGFyayIsImV4cCI6MTY3MDQwMjk4OSwiaWF0IjoxNjY2ODAyOTg5fQ.re57NsDtpw5r60IhYNDV5jJkHlgD6thomEA6enYkJ_U

###

GET http://localhost:8080/boards/17
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoaWhpNCIsImV4cCI6MTY3MDM4OTUyOSwiaWF0IjoxNjY2Nzg5NTI5fQ.gA1nD0_QRav-K0MwzqenZ3OxJTE7abOCxCoH53DWOBA

###

PUT http://localhost:8080/auth/boards/modify/4
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtcGFya2VyIiwiZXhwIjoxNjcwNDU0Mzg2LCJpYXQiOjE2NjY4NTQzODZ9.ANWfx11O1JL8lfWGZ52L9mr4ptTRvlrf4WxjXJBL8S8

{
  "boardTitle": "뽈낑뽈깡 스러운꿈이였바봅니다..."
}

###

DELETE http://localhost:8080/auth/boards/delete/4
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtcGFya2VyIiwiZXhwIjoxNjcwNDU0Mzg2LCJpYXQiOjE2NjY4NTQzODZ9.ANWfx11O1JL8lfWGZ52L9mr4ptTRvlrf4WxjXJBL8S8


###


POST http://localhost:8080/auth/comments/5/create
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtcGFya2VyIiwiZXhwIjoxNjcwNDU0Mzg2LCJpYXQiOjE2NjY4NTQzODZ9.ANWfx11O1JL8lfWGZ52L9mr4ptTRvlrf4WxjXJBL8S8

{
  "comment": "오...귀한 뽈깡뽈낑을...축하드립니다 뽈깡!"
}

###


PUT http://localhost:8080/auth/comments/1/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtcGFya2VyIiwiZXhwIjoxNjcwNDU0Mzg2LCJpYXQiOjE2NjY4NTQzODZ9.ANWfx11O1JL8lfWGZ52L9mr4ptTRvlrf4WxjXJBL8S8

{
  "modifiedComment": "hihihihii"
}

###


DELETE http://localhost:8080/auth/boards/delete/5
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtcGFya2VyIiwiZXhwIjoxNjcwNDU0Mzg2LCJpYXQiOjE2NjY4NTQzODZ9.ANWfx11O1JL8lfWGZ52L9mr4ptTRvlrf4WxjXJBL8S8

###

POST http://localhost:8080/auth/2/DISLIKE
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtcGFya2VyIiwiZXhwIjoxNjcwNDU4MjE3LCJpYXQiOjE2NjY4NTgyMTd9.V_72QhyuSPxcf-uqFOKErm85SAE1QNxM3IX9R1iKxtA


###
POST http://localhost:8080/auth/2/LIKE
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtcGFya2VyIiwiZXhwIjoxNjcwNDU4MjE3LCJpYXQiOjE2NjY4NTgyMTd9.V_72QhyuSPxcf-uqFOKErm85SAE1QNxM3IX9R1iKxtA
###
POST http://localhost:8080/auth/2/HORROR
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtcGFya2VyIiwiZXhwIjoxNjcwNDU4MjE3LCJpYXQiOjE2NjY4NTgyMTd9.V_72QhyuSPxcf-uqFOKErm85SAE1QNxM3IX9R1iKxtA