POST http://localhost:8080/member/register
Content-Type: application/json

{
  "username": "hihi4",
  "nickname": "adam12",
  "password": "bin12345"
}

###

POST http://localhost:8080/member/login
Content-Type: application/json

{
  "username": "hihi4",
  "password": "bin12345"
}

###

POST http://localhost:8080/auth/boards/create
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoaWhpMiIsImV4cCI6MTY2Njc1OTkzOCwiaWF0IjoxNjY2NzU2MzM4fQ.SRtxcv6pCP6BZKkg9SEYSRRwBExdAbjKHSpPgCsatpM

{
  "boardContent": "여덜번쨰 포스트",
  "boardTitle": "졸려"
}





###

GET http://localhost:8080/boards
Content-Type: application/json

###

POST http://localhost:8080/auth/8/reaction/like
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoaWhpMiIsImV4cCI6MTY2Njc3MzI5NiwiaWF0IjoxNjY2NzY5Njk2fQ.rBQhjH-hjbD3urIHpvYP3BCNE-brniQaKT4WEFvUZGc

###

POST http://localhost:8080/auth/4/DISLIKE/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoaWhpMiIsImV4cCI6MTY3MDM3NDIwMiwiaWF0IjoxNjY2Nzc0MjAyfQ.B_05vE7vhFPnq3j3CP7oMfAP-Wqyumw_k06CD4GmVCw




###

GET http://localhost:8080/boards/17
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoaWhpNCIsImV4cCI6MTY3MDM4OTUyOSwiaWF0IjoxNjY2Nzg5NTI5fQ.gA1nD0_QRav-K0MwzqenZ3OxJTE7abOCxCoH53DWOBA

###

PUT http://localhost:8080/auth/boards/modify/2
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0aW5nIiwiZXhwIjoxNjY2NzE5NjgyLCJpYXQiOjE2NjY3MTYwODJ9.iamLpw7poPrZ05Q3_9UoRDU99Qq8ZgD3O_DziPNjgsM

{
  "content": "이것도 테스트용",
  "title": "이건 테스트용"
}

###

DELETE http://localhost:8080/auth/boards/delete/7
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0aW5nMyIsImV4cCI6MTY2Njc1NTQwMywiaWF0IjoxNjY2NzUxODAzfQ.c6ud6k1I5X-nUZ-eyHfop9mNOwF9rGKg-eA6rRqqr7w



###

GET http://localhost:8080/api/member/id/test22ing
Content-Type: application/json


###

DELETE http://localhost:8080/api/auth/boards/4
Content-Type: application/json
Access_Token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0aW5nIiwiZXhwIjoxNjY2NTQ1OTIwLCJpYXQiOjE2NjY1NDIzMjB9.st236wqx5nVjcXQAqF8s_miggDPEwAKHPK1hdIH8mqQ


###

POST http://localhost:8080/auth/comments/17/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoaWhpNCIsImV4cCI6MTY3MDM4OTUyOSwiaWF0IjoxNjY2Nzg5NTI5fQ.gA1nD0_QRav-K0MwzqenZ3OxJTE7abOCxCoH53DWOBA

{
  "comment": "cococooment"
}

###

GET http://localhost:8080/auth/comments/1/isUpdate
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoaWhpMSIsImV4cCI6MTY2Njc1NTk3OSwiaWF0IjoxNjY2NzUyMzc5fQ.is7UDu95PBRl6dq-9cfwgYUToo0UxMS4dIwXZi_hSaE



###

PUT http://localhost:8080/auth/comments/1/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoaWhpMiIsImV4cCI6MTY3MDM3NzgxMSwiaWF0IjoxNjY2Nzc3ODExfQ.FhDLcWpCegsCJTJL5igLrL3qmznE0gUTGJKnXHSWhg0

{
  "modifiedComment": "hihihihii"
}

###


GET http://localhost:8080/api/issue/token
Accept: application/json
Refresh_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3b25iaW4zQGdtYWlsLmNvbSIsImV4cCI6MTY2NjEwMTQzNSwiaWF0IjoxNjY2MDE1MDM1fQ.qoilL1J0v22nDYG7kN-aD665EHUWlIt-nL3PwbUPT-A

###
POST http://localhost:8080/api/member
Content-Type: application/json

{
  "username": "wonbin@mail.com",
  "password": "bin1234"
}

###

GET http://localhost:8080/api/auth/boards
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtU2Vjb25kIiwiZXhwIjoxNjY2MjQ2NTkyLCJpYXQiOjE2NjYxNjAxOTJ9.OnVZUmzEtl_MyIg7hgh-WRLeFkaZZdv5sGE8tKmWEEM

###

DELETE http://localhost:8080/api/auth/boards/delete/1
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtU2Vjb25kIiwiZXhwIjoxNjY2MTg3Mjk4LCJpYXQiOjE2NjYxMDA4OTh9._sVp2TPHOXuBu57FcbKbz-KhUw9A6YjNsI4N_4vR_tg
###

PUT http://localhost:8080/api/auth/boards/update/2
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGFtU2Vjb25kIiwiZXhwIjoxNjY2MjY0NDM0LCJpYXQiOjE2NjYxNzgwMzR9.HDTdREpm8gK4DHnu0Db44E-3WQ620YuvAQ8rZWiqXq4

{
  "title": "zzzz Title"
}

###
POST http://localhost:8080/auth/11/DISLIKE/
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoaWhpNCIsImV4cCI6MTY3MDM4NzY4MSwiaWF0IjoxNjY2Nzg3NjgxfQ.fZ46RtXo6Edj2_h28C7FkExB4qiZpq2pJkSforKy9U0


###
POST http://localhost:8080/auth/11/LIKE/
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoaWhpNCIsImV4cCI6MTY3MDM4NzY4MSwiaWF0IjoxNjY2Nzg3NjgxfQ.fZ46RtXo6Edj2_h28C7FkExB4qiZpq2pJkSforKy9U0

###
POST http://localhost:8080/auth/11/HORROR/
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoaWhpNCIsImV4cCI6MTY3MDM4NzY4MSwiaWF0IjoxNjY2Nzg3NjgxfQ.fZ46RtXo6Edj2_h28C7FkExB4qiZpq2pJkSforKy9U0

